version: '3.8'

services:
  wp-db:
    image: postgres:15
    container_name: players_db
    environment:
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: wp
    ports:
      - "5431:5432"  # Maps host port 5431 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: demo:latest  # Use your latest app image name
    container_name: players_app
    depends_on:
      - wp-db
    ports:
      - "8080:8080"  # Ensure this line is present to map host port 8080 to container port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wp-db:5432/wp
      SPRING_DATASOURCE_USERNAME: wp
      SPRING_DATASOURCE_PASSWORD: wp123

volumes:
  pgdata:
