version: '3.8'

services:
  wp-db:
    image: postgres:15
    container_name: players_db
    environment:
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: wp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: demo:latest
    container_name: players_app
    depends_on:
      - wp-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wp-db:5432/wp
      SPRING_DATASOURCE_USERNAME: wp
      SPRING_DATASOURCE_PASSWORD: wp123

volumes:
  pgdata:
